import { Product } from './types';

// Static product data - add your products here
export const staticProducts: Product[] = [
    {
        id: '1',
        name: 'Gold Plated Anti Tarnish Stainless Steel Bow Themed Pendant',
        slug: 'gold-plated-bow-pendant',
        description: 'Elegant bow-themed pendant crafted from premium stainless steel with anti-tarnish gold plating. Perfect for everyday wear.',
        price: 599.00,
        discountedPrice: 499.00,
        categories: ['necklaces', 'pendants', 'office-girl'],
        tags: ['new', 'trending'],
        material: 'Stainless Steel',
        images: ['/images/products/bow-pendant.jpg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '2',
        name: 'Xuping Jewelry Contemporary Cat Shaped AD Studded Hoop Earrings',
        slug: 'xuping-cat-hoop-earrings',
        description: 'Adorable cat-shaped hoop earrings with AD stone studs. A playful addition to any jewelry collection.',
        price: 599.00,
        discountedPrice: 499.00,
        categories: ['earrings', 'island-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        images: ['/images/products/cat-hoop-earrings.jpg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '3',
        name: 'Gold-Plated Anti Tarnish Stainless Steel Contemporary Adjustable Ring',
        slug: 'contemporary-adjustable-ring',
        description: 'Modern adjustable ring with contemporary design. Anti-tarnish coating ensures lasting shine.',
        price: 449.00,
        discountedPrice: 399.00,
        categories: ['rings', 'office-girl'],
        tags: ['bestseller'],
        material: 'Stainless Steel',
        images: ['/images/products/contemporary-ring.jpg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '4',
        name: 'Gold Plated Stainless Steel Anti Tarnish Green Emerald Studded Adjustable Finger Ring',
        slug: 'emerald-studded-ring',
        description: 'Luxurious adjustable ring featuring a stunning green emerald. Gold plated with anti-tarnish finish.',
        price: 549.00,
        discountedPrice: 449.00,
        categories: ['rings', 'dreamy-girl'],
        tags: ['new'],
        material: 'Stainless Steel',
        stone: 'Emerald',
        images: ['/images/products/emerald-ring.jpg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '5',
        name: 'Gold Plated Stainless Steel Anti Tarnish Snake Chain Green Emerald Studded Wraparound Bracelet',
        slug: 'emerald-wraparound-bracelet',
        description: 'Elegant wraparound bracelet with snake chain design and green emerald accents.',
        price: 699.00,
        discountedPrice: 599.00,
        categories: ['bracelets', 'island-girl'],
        tags: ['trending'],
        material: 'Stainless Steel',
        stone: 'Emerald',
        images: ['/images/products/emerald-wraparound-bracelet.jpg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '6',
        name: 'Stainless Steel Gold Plated Evil Eye Anti-Tarnish Bracelet For Women',
        slug: 'evil-eye-bracelet',
        description: 'Protective evil eye bracelet with gold plating and anti-tarnish coating. A meaningful accessory.',
        price: 499.00,
        discountedPrice: 399.00,
        categories: ['bracelets', 'island-girl'],
        tags: ['bestseller'],
        material: 'Stainless Steel',
        images: ['/images/products/evil-eye-bracelet.jpg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 25,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '7',
        name: 'Gold Plated Stainless Steel Anti Tarnish Evil Eye themed Dual Strand Necklace',
        slug: 'evil-eye-dual-strand-necklace',
        description: 'Beautiful dual strand necklace with evil eye charm. Gold plated for lasting elegance.',
        price: 799.00,
        discountedPrice: 699.00,
        categories: ['necklaces', 'island-girl'],
        tags: ['new'],
        material: 'Stainless Steel',
        images: ['/images/products/evil-eye-necklace.jpg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '8',
        name: 'Gold Plated Anti Tarnish Stainless Steel Floral Themed Cuff Bracelet',
        slug: 'floral-cuff-bracelet',
        description: 'Delicate floral-themed cuff bracelet with intricate detailing. Perfect for special occasions.',
        price: 649.00,
        discountedPrice: 549.00,
        categories: ['bracelets', 'dreamy-girl'],
        tags: ['trending'],
        material: 'Stainless Steel',
        images: ['/images/products/floral-cuff-bracelet.jpg'],
        variants: [],
        featured: false,
        isActive: true,
        stock: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '9',
        name: 'Gold Plated Stainless Steel Anti Tarnish Floral Themed Stud Earrings',
        slug: 'floral-stud-earrings',
        description: 'Charming floral stud earrings with anti-tarnish gold plating. Lightweight and comfortable.',
        price: 399.00,
        discountedPrice: 349.00,
        categories: ['earrings', 'office-girl'],
        tags: ['bestseller'],
        material: 'Stainless Steel',
        images: ['/images/products/floral-stud-earrings.jpg'],
        variants: [],
        featured: false,
        isActive: true,
        stock: 30,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '10',
        name: 'Gold-Plated Anti Tarnish Green Geometric Pendant',
        slug: 'green-geometric-pendant',
        description: 'Modern geometric pendant with vibrant green stone. A statement piece for any outfit.',
        price: 549.00,
        discountedPrice: 449.00,
        categories: ['necklaces', 'pendants', 'dreamy-girl'],
        tags: ['new'],
        material: 'Alloy',
        images: ['/images/products/green-geometric-pendant.jpg'],
        variants: [],
        featured: false,
        isActive: true,
        stock: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '11',
        name: 'Gold-Plated Anti Tarnish Heart Themed Layered Necklace',
        slug: 'heart-layered-necklace',
        description: 'Romantic heart-themed layered necklace. Perfect for gifting or self-expression.',
        price: 699.00,
        discountedPrice: 599.00,
        categories: ['necklaces', 'dreamy-girl'],
        tags: ['trending', 'bestseller'],
        material: 'Stainless Steel',
        images: ['/images/products/heart-layered-necklace.jpg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '12',
        name: 'Gold Plated Stainless Steel Anti Tarnish Heart Themed Stud Earrings',
        slug: 'heart-stud-earrings',
        description: 'Sweet heart-shaped stud earrings with gold plating. A timeless classic.',
        price: 349.00,
        discountedPrice: 299.00,
        categories: ['earrings', 'office-girl'],
        tags: ['bestseller'],
        material: 'Stainless Steel',
        images: ['/images/products/heart-stud-earrings.jpg'],
        variants: [],
        featured: false,
        isActive: true,
        stock: 40,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '13',
        name: 'Gold Plated Anti Tarnish American Diamond Floral Themed Pendant',
        slug: 'ad-floral-themed-pendant',
        description: 'Exquisite floral pendant adorned with sparkling American diamonds. Gold plated with anti-tarnish finish for lasting beauty. A perfect blend of elegance and everyday charm.',
        price: 699.00,
        discountedPrice: 499.00,
        categories: ['necklaces', 'pendants', 'dreamy-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        stone: 'American Diamond',
        images: ['/images/products/ad-floral-pendant.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '14',
        name: 'Gold Plated Anti Tarnish Rose Themed Pendant',
        slug: 'rose-themed-pendant',
        description: 'A beautiful rose-themed pendant with gold plating and anti-tarnish finish. Elegant and timeless, perfect for both daily wear and special occasions.',
        price: 499.00,
        discountedPrice: 299.00,
        categories: ['necklaces', 'pendants', 'office-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        images: ['/images/products/rose-themed-pendant.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '15',
        name: 'Gold-Plated Anti Tarnish White Emerald Geometric Layered Necklace',
        slug: 'white-emerald-geometric-layered-necklace',
        description: 'Stunning geometric layered necklace featuring white emerald stones. Gold plated with anti-tarnish technology for a bold, island-inspired look that lasts.',
        price: 699.00,
        discountedPrice: 499.00,
        categories: ['necklaces', 'island-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        stone: 'White Emerald',
        images: ['/images/products/white-emerald-geometric-necklace.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '16',
        name: 'Gold Plated Stainless Steel Anti Tarnish Dual Strand Geometric Necklace For Women',
        slug: 'dual-strand-geometric-necklace',
        description: 'Bold dual strand necklace with geometric design. Crafted from stainless steel with gold plating and anti-tarnish finish. A statement piece for the modern woman.',
        price: 599.00,
        discountedPrice: 449.00,
        categories: ['necklaces', 'island-girl'],
        tags: ['new', 'trending'],
        material: 'Stainless Steel',
        images: ['/images/products/dual-strand-geometric-necklace.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '17',
        name: 'Gold Plated Stainless Steel Anti Tarnish Teardrop Pendant',
        slug: 'teardrop-pendant',
        description: 'Sleek teardrop pendant crafted from stainless steel with gold plating and anti-tarnish finish. A minimalist yet elegant accessory for everyday office wear.',
        price: 399.00,
        discountedPrice: 199.00,
        categories: ['necklaces', 'pendants', 'office-girl'],
        tags: ['new', 'bestseller'],
        material: 'Stainless Steel',
        images: ['/images/products/teardrop-pendant.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 25,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '18',
        name: 'Gold-Plated Anti Tarnish Black Geometric Pendant',
        slug: 'black-geometric-pendant',
        description: 'Sophisticated black geometric pendant with gold plating and anti-tarnish coating. A modern, minimalist piece ideal for professional settings.',
        price: 499.00,
        discountedPrice: 299.00,
        categories: ['necklaces', 'pendants', 'office-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        images: ['/images/products/black-geometric-pendant.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '19',
        name: 'Gold Plated Stainless Steel Anti Tarnish Tear Drop CZ Dual Strand Pendant',
        slug: 'teardrop-cz-dual-strand-pendant',
        description: 'Elegant teardrop pendant with sparkling CZ stones on a dual strand chain. Crafted from stainless steel with gold plating and anti-tarnish finish for everyday sophistication.',
        price: 599.00,
        discountedPrice: 499.00,
        categories: ['necklaces', 'pendants', 'office-girl'],
        tags: ['new', 'trending'],
        material: 'Stainless Steel',
        stone: 'Cubic Zirconia',
        images: ['/images/products/teardrop-cz-dual-strand-pendant.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '20',
        name: 'Anti-Tarnish Multilayer Chain Necklace with American Diamond Elegant Long Pendant',
        slug: 'multilayer-ad-long-pendant',
        description: 'Eye-catching multilayer chain necklace featuring an elegant long pendant with American diamond accents. Anti-tarnish finish ensures lasting brilliance for a bold island-inspired style.',
        price: 699.00,
        discountedPrice: 499.00,
        categories: ['necklaces', 'pendants', 'island-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        stone: 'American Diamond',
        images: ['/images/products/multilayer-ad-long-pendant.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '21',
        name: 'Gold-Plated Anti Tarnish Heart Themed Pendant',
        slug: 'heart-themed-pendant',
        description: 'Charming heart-themed pendant with gold plating and anti-tarnish finish. A sweet and elegant accessory perfect for everyday office wear.',
        price: 299.00,
        discountedPrice: 199.00,
        categories: ['necklaces', 'pendants', 'office-girl'],
        tags: ['new', 'bestseller'],
        material: 'Alloy',
        images: ['/images/products/heart-themed-pendant.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 30,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '22',
        name: 'Gold-Plated Anti Tarnish Heart & Cube Themed Pendant',
        slug: 'heart-cube-themed-pendant',
        description: 'Unique heart and cube themed pendant with gold plating and anti-tarnish coating. A creative blend of geometric and romantic design for the modern professional.',
        price: 499.00,
        discountedPrice: 299.00,
        categories: ['necklaces', 'pendants', 'office-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        images: ['/images/products/heart-cube-themed-pendant.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '23',
        name: 'Gold Plated Anti Tarnish Stainless Steel Evil Eye Themed Multicolor Pendant',
        slug: 'evil-eye-multicolor-pendant',
        description: 'Vibrant multicolor evil eye pendant crafted from stainless steel with gold plating and anti-tarnish finish. A protective and stylish accessory with bold island vibes.',
        price: 599.00,
        discountedPrice: 399.00,
        categories: ['necklaces', 'pendants', 'island-girl'],
        tags: ['new', 'trending'],
        material: 'Stainless Steel',
        images: ['/images/products/evil-eye-multicolor-pendant.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '24',
        name: 'Gold Plated Anti Tarnish Stainless Steel Evil Eye Themed Pendant',
        slug: 'evil-eye-themed-pendant',
        description: 'Classic evil eye pendant crafted from stainless steel with gold plating and anti-tarnish finish. A meaningful and stylish accessory with island-inspired charm.',
        price: 499.00,
        discountedPrice: 349.00,
        categories: ['necklaces', 'pendants', 'island-girl'],
        tags: ['new', 'trending'],
        material: 'Stainless Steel',
        images: ['/images/products/evil-eye-themed-pendant.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '25',
        name: 'Gold-Plated Anti Tarnish Stainless Steel Evil Eye Themed Multicolor Pendant',
        slug: 'gold-plated-evil-eye-multicolor-pendant',
        description: 'Stunning multicolor evil eye pendant with gold plating and anti-tarnish stainless steel construction. A vibrant island-girl accessory that combines protection with style.',
        price: 499.00,
        discountedPrice: 349.00,
        categories: ['necklaces', 'pendants', 'island-girl'],
        tags: ['new', 'trending'],
        material: 'Stainless Steel',
        images: ['/images/products/evil-eye-multicolor-pendant-v2.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '26',
        name: 'Musicar Gold-Plated Anti Tarnish Premium Stone-Studded Designer Bangle for Women and Girls Elegant Twisted-Side Bracelet Sparkling Stones Fashion',
        slug: 'stone-studded-designer-bangle',
        description: 'Premium stone-studded designer bangle with elegant twisted-side design. Gold plated with anti-tarnish finish and sparkling stones for a sophisticated office look.',
        price: 699.00,
        discountedPrice: 499.00,
        categories: ['bracelets', 'office-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        stone: 'CZ Stone',
        images: ['/images/products/stone-studded-designer-bangle.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '27',
        name: 'Musicar Premium Bracelet Anti Tarnish 18k Gold Plated Stainless Steel Waterproof Trending Design',
        slug: 'premium-18k-bracelet',
        description: 'Premium 18k gold plated bracelet crafted from stainless steel with anti-tarnish and waterproof properties. A trending design perfect for the modern office professional.',
        price: 699.00,
        discountedPrice: 499.00,
        categories: ['bracelets', 'office-girl'],
        tags: ['new', 'trending'],
        material: 'Stainless Steel',
        images: ['/images/products/premium-18k-bracelet.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '28',
        name: 'Musicar Elegant Crystal-Studded Anti Tarnish Bangle Bracelet, Two-Tone Geometric Pattern',
        slug: 'crystal-studded-bangle',
        description: 'Elegant crystal-studded bangle bracelet with a striking two-tone geometric pattern. Anti-tarnish finish ensures lasting beauty for bold island-inspired styling.',
        price: 599.00,
        discountedPrice: 399.00,
        categories: ['bracelets', 'island-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        stone: 'Crystal',
        images: ['/images/products/crystal-studded-bangle.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '29',
        name: 'Anti Tarnish Luxury Gold Plated Free Size Stylish Cuff Bangle Bracelet',
        slug: 'luxury-cuff-bangle',
        description: 'Luxurious gold plated cuff bangle bracelet with free size adjustable fit. Anti-tarnish finish ensures lasting elegance for a dreamy, sophisticated look.',
        price: 899.00,
        discountedPrice: 599.00,
        categories: ['bracelets', 'dreamy-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        images: ['/images/products/luxury-cuff-bangle.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '30',
        name: 'Anti Tarnish Jewellery Stainless Steel Cuff Bracelet',
        slug: 'ss-cuff-bracelet',
        description: 'Sleek stainless steel cuff bracelet with anti-tarnish finish. A versatile and durable accessory perfect for everyday office wear.',
        price: 499.00,
        discountedPrice: 399.00,
        categories: ['bracelets', 'office-girl'],
        tags: ['new', 'bestseller'],
        material: 'Stainless Steel',
        images: ['/images/products/ss-cuff-bracelet.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '31',
        name: 'Inventive Arts Latest Gold Plated Bracelet Anti Tarnish Stylish Adjustable Bangles Kada Cuff',
        slug: 'gold-plated-adjustable-bangle',
        description: 'Stylish adjustable bangle with gold plating and anti-tarnish finish. A dreamy kada cuff design perfect for adding a touch of elegance to any outfit.',
        price: 399.00,
        discountedPrice: 299.00,
        categories: ['bracelets', 'dreamy-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        images: ['/images/products/gold-plated-adjustable-bangle.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 22,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '32',
        name: 'Gold Plated Chunky Chain Bracelet for Women & Girls',
        slug: 'chunky-chain-bracelet',
        description: 'Bold chunky chain bracelet with gold plating. A statement piece that adds island-inspired flair to any look.',
        price: 399.00,
        discountedPrice: 299.00,
        categories: ['bracelets', 'island-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        images: ['/images/products/chunky-chain-bracelet.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '33',
        name: 'Anti-Tarnish Gold Eye Motif Bracelet for Women',
        slug: 'gold-eye-motif-bracelet',
        description: 'Stylish gold eye motif bracelet with anti-tarnish finish. A unique and meaningful accessory with bold island-inspired charm.',
        price: 399.00,
        discountedPrice: 299.00,
        categories: ['bracelets', 'island-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        images: ['/images/products/gold-eye-motif-bracelet.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '34',
        name: 'Gold-Plated Nail Cuff Bracelet Anti-Tarnish Stainless Steel Open Bangle for Women',
        slug: 'nail-cuff-bracelet',
        description: 'Chic nail cuff bracelet crafted from stainless steel with gold plating and anti-tarnish finish. A sleek open bangle design perfect for professional office style.',
        price: 499.00,
        discountedPrice: 299.00,
        categories: ['bracelets', 'office-girl'],
        tags: ['new', 'trending'],
        material: 'Stainless Steel',
        images: ['/images/products/nail-cuff-bracelet.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '35',
        name: 'Gold-Tone Textured Cuff Bracelet for Women – Elegant Adjustable Open Bangle',
        slug: 'textured-cuff-bracelet',
        description: 'Elegant textured cuff bracelet with a gold-tone finish. Adjustable open bangle design for a dreamy, sophisticated look.',
        price: 399.00,
        discountedPrice: 249.00,
        categories: ['bracelets', 'dreamy-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        images: ['/images/products/textured-cuff-bracelet.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '36',
        name: 'Gold Plated Geometric Statement Cuff Bracelet for Women',
        slug: 'geometric-statement-cuff',
        description: 'Bold geometric statement cuff bracelet with gold plating. A powerful accessory that elevates your professional office look.',
        price: 599.00,
        discountedPrice: 399.00,
        categories: ['bracelets', 'office-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        images: ['/images/products/geometric-statement-cuff.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '37',
        name: 'Galaxy Jewellery For Women Gold-Toned Gold Plated Locke Bracelet',
        slug: 'gold-toned-locke-bracelet',
        description: 'Elegant gold-toned locke bracelet with gold plating. A refined and polished accessory perfect for the modern office professional.',
        price: 499.00,
        discountedPrice: 349.00,
        categories: ['bracelets', 'office-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        images: ['/images/products/gold-toned-locke-bracelet.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '38',
        name: 'Gold Plated Stainless Steel Anti Tarnish Star Themed Bracelet For Women',
        slug: 'star-themed-bracelet',
        description: 'Dazzling star themed bracelet crafted from stainless steel with gold plating and anti-tarnish finish. A celestial accessory with bold island-girl energy.',
        price: 699.00,
        discountedPrice: 449.00,
        categories: ['bracelets', 'island-girl'],
        tags: ['new', 'trending'],
        material: 'Stainless Steel',
        images: ['/images/products/star-themed-bracelet.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '39',
        name: 'Multi Strand Evil Eye AD Gold Plated Charm Bracelet For Women',
        slug: 'multi-strand-evil-eye-charm-bracelet',
        description: 'Eye-catching multi strand charm bracelet featuring evil eye motifs with American diamond accents and gold plating. A bold island-girl statement piece.',
        price: 599.00,
        discountedPrice: 399.00,
        categories: ['bracelets', 'island-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        stone: 'American Diamond',
        images: ['/images/products/multi-strand-evil-eye-bracelet.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '40',
        name: 'Gold Plated Set Of 6 Charm Bracelet for Women And Girls',
        slug: 'set-of-6-charm-bracelet',
        description: 'Gorgeous set of 6 charm bracelets with gold plating. Mix and match for endless styling possibilities with island-girl vibes.',
        price: 499.00,
        discountedPrice: 299.00,
        categories: ['bracelets', 'island-girl'],
        tags: ['new', 'bestseller'],
        material: 'Alloy',
        images: ['/images/products/set-of-6-charm-bracelet.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '41',
        name: 'Gold-Toned Gold Plated Contemporary Stackable Bracelet (Pack of 4)',
        slug: 'stackable-bracelet-pack',
        description: 'Contemporary stackable bracelet set with gold plating. Pack of 4 beautifully coordinated pieces for a dreamy layered look.',
        price: 499.00,
        discountedPrice: 299.00,
        categories: ['bracelets', 'dreamy-girl'],
        tags: ['new', 'bestseller'],
        material: 'Alloy',
        images: ['/images/products/stackable-bracelet-pack.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '42',
        name: 'Gold Plated Contemporary Bracelet (Pack of 4)',
        slug: 'contemporary-bracelet-pack',
        description: 'Stylish contemporary bracelet set with gold plating. Pack of 4 versatile pieces for effortless island-girl layering.',
        price: 499.00,
        discountedPrice: 299.00,
        categories: ['bracelets', 'island-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        images: ['/images/products/contemporary-bracelet-pack.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '43',
        name: 'Scintillating American Diamond Star & Moon Design Gold Plated Bracelet - Pack Of 4',
        slug: 'star-moon-bracelet-pack',
        description: 'Enchanting star and moon design bracelet set with sparkling American diamonds and gold plating. Pack of 4 dreamy pieces for celestial styling.',
        price: 499.00,
        discountedPrice: 199.00,
        categories: ['bracelets', 'dreamy-girl'],
        tags: ['new', 'bestseller'],
        material: 'Alloy',
        stone: 'American Diamond',
        images: ['/images/products/star-moon-bracelet-pack.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '44',
        name: 'Gold Toned Gold Plated Contemporary Stackable Bracelet (Pack of 4)',
        slug: 'gold-toned-stackable-bracelet',
        description: 'Contemporary stackable bracelet set with gold toned plating. Pack of 4 elegant pieces perfect for a polished office look.',
        price: 499.00,
        discountedPrice: 299.00,
        categories: ['bracelets', 'office-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        images: ['/images/products/gold-toned-stackable-bracelet.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '45',
        name: 'Anti Tarnish Gold Plated Heart Stud Earrings for Women',
        slug: 'gold-plated-heart-stud-earrings',
        description: 'Adorable heart stud earrings with gold plating and anti-tarnish finish. A delicate and charming accessory for everyday office elegance.',
        price: 499.00,
        discountedPrice: 299.00,
        categories: ['earrings', 'office-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        images: ['/images/products/heart-stud-earrings.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '46',
        name: 'Heart Shape Gold Plated Stainless Steel Earrings for Women and Girls',
        slug: 'heart-shape-ss-earrings',
        description: 'Beautiful heart-shaped earrings crafted from stainless steel with gold plating. A dreamy and romantic accessory for women and girls.',
        price: 599.00,
        discountedPrice: 349.00,
        categories: ['earrings', 'dreamy-girl'],
        tags: ['new', 'trending'],
        material: 'Stainless Steel',
        images: ['/images/products/heart-shape-ss-earrings.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '47',
        name: 'Elegant Circular Unique Metal Brilliant Drop Earring For Women And Girls',
        slug: 'circular-drop-earring',
        description: 'Unique circular drop earrings with brilliant metal finish. An elegant and eye-catching accessory perfect for the office girl.',
        price: 349.00,
        discountedPrice: 199.00,
        categories: ['earrings', 'office-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        images: ['/images/products/circular-drop-earring.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 22,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '48',
        name: 'Gold Plated Floral Stud Earrings for Women | Anti Tarnish Stainless Steel Flower Design',
        slug: 'floral-stud-earrings',
        description: 'Delicate floral stud earrings with gold plating and anti-tarnish stainless steel construction. A dreamy flower design for effortless elegance.',
        price: 599.00,
        discountedPrice: 349.00,
        categories: ['earrings', 'dreamy-girl'],
        tags: ['new', 'trending'],
        material: 'Stainless Steel',
        images: ['/images/products/floral-stud-earrings.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '49',
        name: 'Gold Plated Simple Triangle Shaped Latest Trendy Stylish Stud Earrings for Women Girls',
        slug: 'triangle-stud-earrings',
        description: 'Minimalist triangle-shaped stud earrings with gold plating. A trendy and stylish geometric design perfect for office wear.',
        price: 499.00,
        discountedPrice: 299.00,
        categories: ['earrings', 'office-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        images: ['/images/products/triangle-stud-earrings.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 25,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '50',
        name: 'Anti Tarnish Gold Plated Star Earrings for Women',
        slug: 'gold-plated-star-earrings',
        description: 'Stunning star-shaped earrings with gold plating and anti-tarnish finish. A celestial accessory with bold island-girl charm.',
        price: 499.00,
        discountedPrice: 299.00,
        categories: ['earrings', 'island-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        images: ['/images/products/gold-plated-star-earrings.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '51',
        name: 'Unique Ocean-Inspired Designs Anti Tarnish Gold Plated Earrings for Women',
        slug: 'ocean-inspired-earrings',
        description: 'Unique ocean-inspired earrings with gold plating and anti-tarnish finish. A bold island-girl accessory that captures the beauty of the sea.',
        price: 499.00,
        discountedPrice: 399.00,
        categories: ['earrings', 'island-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        images: ['/images/products/ocean-inspired-earrings.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '52',
        name: 'Gold Plated Bow Stud Earrings for Women Anti Tarnish Stainless Steel Ribbon Design Studs',
        slug: 'bow-stud-earrings',
        description: 'Charming bow stud earrings with gold plating and anti-tarnish stainless steel construction. A dreamy ribbon design for effortless feminine style.',
        price: 499.00,
        discountedPrice: 399.00,
        categories: ['earrings', 'dreamy-girl'],
        tags: ['new', 'trending'],
        material: 'Stainless Steel',
        images: ['/images/products/bow-stud-earrings.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '53',
        name: 'Stainless Steel Open Heart Earrings for Women and Girls, Anti-Tarnish',
        slug: 'open-heart-earrings',
        description: 'Elegant open heart earrings crafted from stainless steel with anti-tarnish finish. A timeless and sophisticated accessory for the office girl.',
        price: 499.00,
        discountedPrice: 299.00,
        categories: ['earrings', 'office-girl'],
        tags: ['new', 'bestseller'],
        material: 'Stainless Steel',
        images: ['/images/products/open-heart-earrings.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 22,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '54',
        name: 'Elegant Bow Earrings for Women – Hypoallergenic Stainless Steel Anti Tarnish',
        slug: 'elegant-bow-earrings',
        description: 'Refined bow earrings crafted from hypoallergenic stainless steel with anti-tarnish finish. A sophisticated office-ready accessory.',
        price: 599.00,
        discountedPrice: 349.00,
        categories: ['earrings', 'office-girl'],
        tags: ['new', 'trending'],
        material: 'Stainless Steel',
        images: ['/images/products/elegant-bow-earrings.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '55',
        name: 'Latest Stylish Fancy Gold Plated Anti Tarnish Jewellery Celebrity Inspired Simple Plain Link Chain Chunky Huggie Hoop Trendy Earrings for Women & Girls',
        slug: 'chunky-huggie-hoop-earrings',
        description: 'Celebrity-inspired chunky huggie hoop earrings with gold plating and anti-tarnish finish. A trendy link chain design perfect for the fashion-forward office girl.',
        price: 599.00,
        discountedPrice: 399.00,
        categories: ['earrings', 'office-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        images: ['/images/products/chunky-huggie-hoop-earrings.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '56',
        name: 'Gold Plated American Diamond Studded Contemporary Beautiful Hoop Earrings',
        slug: 'ad-studded-hoop-earrings',
        description: 'Contemporary hoop earrings studded with sparkling American diamonds and gold plating. A beautiful blend of office elegance and dreamy charm.',
        price: 599.00,
        discountedPrice: 399.00,
        categories: ['earrings', 'office-girl', 'dreamy-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        stone: 'American Diamond',
        images: ['/images/products/ad-studded-hoop-earrings.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '57',
        name: 'Gold Plated Anti Tarnish Heart Themed Earrings',
        slug: 'heart-themed-earrings',
        description: 'Lovely heart themed earrings with gold plating and anti-tarnish finish. A romantic accessory that suits both office elegance and dreamy vibes.',
        price: 599.00,
        discountedPrice: 299.00,
        categories: ['earrings', 'office-girl', 'dreamy-girl'],
        tags: ['new', 'bestseller'],
        material: 'Alloy',
        images: ['/images/products/heart-themed-earrings.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '58',
        name: 'Xuping Jewelry Heart Themed AD Studded Contemporary Stud Earrings',
        slug: 'heart-ad-stud-earrings',
        description: 'Contemporary stud earrings with heart theme and American diamond studding. A versatile piece for both office elegance and dreamy styling.',
        price: 599.00,
        discountedPrice: 349.00,
        categories: ['earrings', 'office-girl', 'dreamy-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        stone: 'American Diamond',
        images: ['/images/products/heart-ad-stud-earrings.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '59',
        name: 'Xuping Jewelry Contemporary Geometric AD Studded Hoop Earrings',
        slug: 'geometric-ad-hoop-earrings',
        description: 'Sleek geometric hoop earrings studded with American diamonds. A contemporary and sophisticated accessory for the office girl.',
        price: 499.00,
        discountedPrice: 299.00,
        categories: ['earrings', 'office-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        stone: 'American Diamond',
        images: ['/images/products/geometric-ad-hoop-earrings.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '60',
        name: 'Rose Gold Plated American Diamond Studded Floral Korean Stud Earrings',
        slug: 'rose-gold-floral-stud-earrings',
        description: 'Gorgeous rose gold plated Korean stud earrings with floral design and American diamond studding. A delicate and trendy accessory for the office girl.',
        price: 399.00,
        discountedPrice: 249.00,
        categories: ['earrings', 'office-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        stone: 'American Diamond',
        images: ['/images/products/rose-gold-floral-stud-earrings.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '61',
        name: 'Silver Plated American Diamond Studded Butterfly Shape Korean Hoop Earrings',
        slug: 'butterfly-hoop-earrings',
        description: 'Exquisite butterfly shape hoop earrings with silver plating and American diamond studding. A whimsical yet professional Korean-style accessory.',
        price: 399.00,
        discountedPrice: 199.00,
        categories: ['earrings', 'office-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        stone: 'American Diamond',
        images: ['/images/products/butterfly-hoop-earrings.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '62',
        name: 'Rose Gold Plated American Diamond Studded Heart Shape Korean Stud Earrings',
        slug: 'rose-gold-heart-stud-earrings',
        description: 'Lovely heart-shaped Korean stud earrings with rose gold plating and American diamond studding. A romantic and elegant office accessory.',
        price: 399.00,
        discountedPrice: 249.00,
        categories: ['earrings', 'office-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        stone: 'American Diamond',
        images: ['/images/products/rose-gold-heart-stud-earrings.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '63',
        name: 'Silver Plated American Diamond Studded Geometrical Korean Hoop Earrings',
        slug: 'geometrical-korean-hoop-earrings',
        description: 'Chic geometrical Korean hoop earrings with silver plating and American diamond studding. A modern and sophisticated accessory for the office girl.',
        price: 399.00,
        discountedPrice: 199.00,
        categories: ['earrings', 'office-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        stone: 'American Diamond',
        images: ['/images/products/geometrical-korean-hoop-earrings.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '64',
        name: 'Xuping Jewelry Contemporary Square Shaped AD Studded Hoop Earrings',
        slug: 'square-ad-hoop-earrings',
        description: 'Contemporary square-shaped hoop earrings with American diamond studding. A bold geometric design for the fashion-forward office girl.',
        price: 399.00,
        discountedPrice: 249.00,
        categories: ['earrings', 'office-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        stone: 'American Diamond',
        images: ['/images/products/square-ad-hoop-earrings.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '65',
        name: 'Xuping Jewelry AD Studded Contemporary Stud Earrings',
        slug: 'ad-contemporary-stud-earrings',
        description: 'Elegant contemporary stud earrings with American diamond studding. A minimalist yet sparkling accessory perfect for the office girl.',
        price: 399.00,
        discountedPrice: 199.00,
        categories: ['earrings', 'office-girl'],
        tags: ['new', 'bestseller'],
        material: 'Alloy',
        stone: 'American Diamond',
        images: ['/images/products/ad-contemporary-stud-earrings.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 22,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '66',
        name: 'Gold Plated Anti Tarnish Adjustable Finger Ring for Women & Girls',
        slug: 'gold-plated-adjustable-ring',
        description: 'Elegant gold plated adjustable finger ring with anti-tarnish finish. A versatile and stylish accessory perfect for the office girl.',
        price: 499.00,
        discountedPrice: 299.00,
        categories: ['rings', 'office-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        images: ['/images/products/gold-plated-adjustable-ring.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '67',
        name: '18K Gold Plated Elegant Glam Star Adjustable Ring For Women And Girls',
        slug: 'glam-star-adjustable-ring',
        description: 'Glamorous star-shaped adjustable ring with 18K gold plating. A dreamy celestial accessory for women and girls.',
        price: 499.00,
        discountedPrice: 299.00,
        categories: ['rings', 'dreamy-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        images: ['/images/products/glam-star-adjustable-ring.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '68',
        name: 'Gold Plated Adjustable Leaf Design Ring for Women & Girls',
        slug: 'leaf-design-ring',
        description: 'Nature-inspired leaf design adjustable ring with gold plating. A beautiful island-girl accessory for women and girls.',
        price: 499.00,
        discountedPrice: 299.00,
        categories: ['rings', 'island-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        images: ['/images/products/leaf-design-ring.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '69',
        name: 'Starfish Open Finger Ring | Statement Rings For Women',
        slug: 'starfish-open-ring',
        description: 'Unique starfish open finger ring. A bold statement piece with island-girl energy, perfect for beach-inspired styling.',
        price: 399.00,
        discountedPrice: 249.00,
        categories: ['rings', 'island-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        images: ['/images/products/starfish-open-ring.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '70',
        name: 'Gold Plated Serpent Design CZ Stone Adjustable Waterproof Anti Tarnish Luxury Fashion Jewellery',
        slug: 'serpent-design-ring',
        description: 'Luxurious serpent design adjustable ring with CZ stone, gold plating, waterproof and anti-tarnish finish. A bold office-ready statement piece.',
        price: 399.00,
        discountedPrice: 299.00,
        categories: ['rings', 'office-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        stone: 'CZ Stone',
        images: ['/images/products/serpent-design-ring.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '71',
        name: 'Rings for Woman Girls Stylish Party Wear Version Of Small Fresh Temperament Diamond Leaf Open',
        slug: 'diamond-leaf-open-ring',
        description: 'Stylish diamond leaf open ring with a fresh and elegant temperament. A versatile party-wear accessory perfect for the office girl.',
        price: 399.00,
        discountedPrice: 299.00,
        categories: ['rings', 'office-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        stone: 'Diamond',
        images: ['/images/products/diamond-leaf-open-ring.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '72',
        name: 'Butterfly Design Gold Plated AD Adjustable Ring',
        slug: 'butterfly-ad-adjustable-ring',
        description: 'Enchanting butterfly design adjustable ring with gold plating and American diamond accents. A dreamy and whimsical accessory.',
        price: 399.00,
        discountedPrice: 249.00,
        categories: ['rings', 'dreamy-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        stone: 'American Diamond',
        images: ['/images/products/butterfly-ad-adjustable-ring.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '73',
        name: 'Rose Gold Plated Cross Shaped American Diamond Studded Korean Finger Ring',
        slug: 'cross-shaped-korean-ring',
        description: 'Elegant cross-shaped Korean finger ring with rose gold plating and American diamond studding. A refined office-girl accessory.',
        price: 399.00,
        discountedPrice: 249.00,
        categories: ['rings', 'office-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        stone: 'American Diamond',
        images: ['/images/products/cross-shaped-korean-ring.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '74',
        name: 'Elegant Gold Plated Leaf Design Ring, Adjustable Band, Nature Inspired Statement Fashion Jewelry for Women',
        slug: 'elegant-leaf-design-ring',
        description: 'Nature-inspired leaf design ring with elegant gold plating and adjustable band. A statement fashion piece perfect for the office girl.',
        price: 399.00,
        discountedPrice: 199.00,
        categories: ['rings', 'office-girl'],
        tags: ['new', 'bestseller'],
        material: 'Alloy',
        images: ['/images/products/elegant-leaf-design-ring.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 22,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '75',
        name: 'Leaf Wrap Ring for Women Dainty Adjustable Branch Ring',
        slug: 'leaf-wrap-ring',
        description: 'Dainty leaf wrap ring with adjustable branch design. A delicate nature-inspired accessory perfect for the office girl.',
        price: 399.00,
        discountedPrice: 199.00,
        categories: ['rings', 'office-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        images: ['/images/products/leaf-wrap-ring.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '76',
        name: 'Geometric Y Drop Necklace for Women Minimal Square Pendant Chain',
        slug: 'geometric-y-drop-necklace',
        description: 'Minimalist geometric Y drop necklace with square pendant chain design. A sleek and modern office-girl accessory.',
        price: 499.00,
        discountedPrice: 299.00,
        categories: ['necklaces', 'office-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        images: ['/images/products/geometric-y-drop-necklace.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '77',
        name: 'Gold Plated Anti Tarnish Bow Knot Heart Themed Pendant',
        slug: 'bow-knot-heart-pendant',
        description: 'Charming bow knot heart themed pendant with gold plating and anti-tarnish finish. A dreamy and romantic necklace accessory.',
        price: 599.00,
        discountedPrice: 399.00,
        categories: ['necklaces', 'pendants', 'dreamy-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        images: ['/images/products/bow-knot-heart-pendant.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '78',
        name: 'Gold Plated Leaf Pendant Necklace for Women & Girls Anti-Tarnish Waterproof Stainless Steel Chain',
        slug: 'leaf-pendant-necklace',
        description: 'Elegant leaf pendant necklace with gold plating, anti-tarnish waterproof stainless steel chain. A nature-inspired office-girl essential.',
        price: 599.00,
        discountedPrice: 349.00,
        categories: ['necklaces', 'pendants', 'office-girl'],
        tags: ['new', 'trending'],
        material: 'Stainless Steel',
        images: ['/images/products/leaf-pendant-necklace.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '79',
        name: 'Luxury Gold Plated Heart Pendant Necklace for Women',
        slug: 'luxury-heart-pendant-necklace',
        description: 'Luxurious gold plated heart pendant necklace. A dreamy and romantic statement piece for women who love elegance.',
        price: 599.00,
        discountedPrice: 349.00,
        categories: ['necklaces', 'pendants', 'dreamy-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        images: ['/images/products/luxury-heart-pendant-necklace.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '80',
        name: 'Anti Tarnish Four - Clover Pendant Necklace for Girls & Women',
        slug: 'four-clover-pendant-necklace',
        description: 'Lucky four-clover pendant necklace with anti-tarnish finish. A timeless and elegant office-girl accessory for girls and women.',
        price: 599.00,
        discountedPrice: 349.00,
        categories: ['necklaces', 'pendants', 'office-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        images: ['/images/products/four-clover-pendant-necklace.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '81',
        name: 'Gold Plated Angel Wings Adjustable Open Ring for Womens',
        slug: 'angel-wings-open-ring',
        description: 'Stunning angel wings adjustable open ring with gold plating. A graceful and heavenly accessory for the office girl.',
        price: 399.00,
        discountedPrice: 249.00,
        categories: ['rings', 'office-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        images: ['/images/products/angel-wings-open-ring.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: '82',
        name: 'Rose Gold Plated American Studded Floral Adjustable Finger Ring for Women & Girls',
        slug: 'rose-gold-floral-ring',
        description: 'Beautiful rose gold plated floral adjustable finger ring with American diamond studding. A delicate and elegant office-girl accessory.',
        price: 399.00,
        discountedPrice: 249.00,
        categories: ['rings', 'office-girl'],
        tags: ['new', 'trending'],
        material: 'Alloy',
        stone: 'American Diamond',
        images: ['/images/products/rose-gold-floral-ring.jpeg'],
        variants: [],
        featured: true,
        isActive: true,
        stock: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
];

// Get all active products
export async function getProducts(): Promise<Product[]> {
    return staticProducts.filter(p => p.isActive);
}

// Get featured products
export async function getFeaturedProducts(): Promise<Product[]> {
    return staticProducts.filter(p => p.isActive && p.featured);
}

// Get products by category
export async function getProductsByCategory(category: string): Promise<Product[]> {
    return staticProducts.filter(p =>
        p.isActive &&
        (p.categories?.includes(category) || p.category === category)
    );
}

// Get product by slug
export function getProductBySlug(slug: string): Product | undefined {
    return staticProducts.find(p => p.slug === slug);
}

// Get product by ID
export function getProductById(id: string): Product | undefined {
    return staticProducts.find(p => p.id === id);
}

// Search products
export function searchProducts(query: string): Product[] {
    const lowercaseQuery = query.toLowerCase();
    return staticProducts.filter(
        (p) =>
            p.isActive &&
            (p.name.toLowerCase().includes(lowercaseQuery) ||
                p.description.toLowerCase().includes(lowercaseQuery) ||
                p.tags.some((tag) => tag.toLowerCase().includes(lowercaseQuery)) ||
                (p.material && p.material.toLowerCase().includes(lowercaseQuery)) ||
                (p.stone && p.stone.toLowerCase().includes(lowercaseQuery)))
    );
}
